### ISSUE TITLE
news project. error: Target of URI doesn't exist: 'package:test/test.dart'

### ISSUE THREAD

**Issue by rustkas** [StephenGrider/FlutterCasts#6]
If you've upgraded to a recent master, you'll find that flutter_test has removed its dependency on package:test. The package hasn't been removed or renamed, but you will need to specifically add it to you dev_dependencies in your pubspec now:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4
```
[more info](https://stackoverflow.com/questions/53208676/error-target-of-uri-doesnt-exist-packagetest-test-dart)
